### JAZZ provider
GET http://flights.beta.bcmenergy.fr/jazz/flights?departure_airport=CDG&arrival_airport=LHR&departure_date=2019-03-28

#### MOON provider
GET http://flights.beta.bcmenergy.fr/moon/flights?departure_airport=CDG&arrival_airport=LHR&departure_date=2019-03-28

###
GET http://localhost:3000/api/v1/

### Auth
POST http://localhost:3000/api/v1/user/signIn HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "password123admin"
}

###

GET http://localhost:3000/api/v1/flights?departure_airport=CDG&arrival_airport=LHR&departure_date=2019-03-28&return_date=2019-03-28&tripType=R
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwicGFzc3dvcmQiOiJwYXNzd29yZDEyM2FkbWluIiwiaWF0IjoxNTgxNTM5MTMwLCJleHAiOjE1ODE1Mzk0MzB9.gacp_PpvtyN8i9-_lQfP-DiPANa8gdZOXNZ7HHxigoI

###
GET http://localhost:3000/api/v1/flights?departure_airport=CDG&arrival_airport=LHR&departure_date=2019-03-28&tripType=OW
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwicGFzc3dvcmQiOiJwYXNzd29yZDEyM2FkbWluIiwiaWF0IjoxNTgxNTQ3MDMxLCJleHAiOjE1ODE1NDczMzF9.R00ckQBVPw2W2uLeTL1ksGQBThM25FFAxv0Tbg0BBhc